version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=hiiKt1TjQbNjYdfi
      - DB_NAME=patient_management
      - JWT_SECRET=LUtFvBbMYwx0vXnf
      - JWT_EXPIRATION=24h
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
    networks:
      - patient-network

  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hiiKt1TjQbNjYdfi
      - POSTGRES_DB=patient_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - patient-network

volumes:
  postgres-data:

networks:
  patient-network:
    driver: bridge
